HCompV: {F: 0.01}
HCopy: {CEPLIFTER: 22, ENORMALIZE: T, NUMCEPS: 12, NUMCHANS: 20, PREEMCOEF: 0.97,
  SOURCEFORMAT: WAVE, SOURCEKIND: WAVEFORM, TARGETKIND: MFCC_D_A_0, TARGETRATE: 100000.0,
  USEHAMMING: T, WINDOWSIZE: 250000.0}
HERest: {CEPLIFTER: 22, ENORMALIZE: T, NUMCEPS: 12, NUMCHANS: 20, PREEMCOEF: 0.97,
  TARGETKIND: MFCC_D_A_0, TARGETRATE: 100000.0, USEHAMMING: T, WINDOWSIZE: 250000.0}
HVite: {SFAC: 5}
URL: http://prosodylab.org/tools/aligner/
authors: Kyle Gorman, Sarah Mihuc, Hannah Cohen
citation: 'K. Gorman, J. Howell, and M. Wagner. 2011. Prosodylab-Aligner: A tool for
  forced alignment of laboratory speech. Canadian Acoustics, 39(3), 192-193.'
epochs: 10
language: French
phoneset: [a, AN, E, e, neuf, deux, i, O, o, u, huit, ^, y, cinq, N, b, d, f, g, G,
  j, k, l, m, n, p, R, s, S, t, to, un, v, w, x, z, Z]
pruning: [250, 100, 4000]
samplerate: 10000
